### ISSUE TITLE
Disable RTL

### ISSUE THREAD

**Issue by adin234** [bkhezry/PersianSearchableSpinner#1]
can we disable rtl? i was supposed to use the library this was based in but it uses minSdk 21. i saw this fork and it uses 17 so i want to use it instead. but i think it is only RTL right now

**Comment by bkhezry** [comment]
Hi @adin234 
No I can not. this library refactoring for Persian language that is RTL. 
I want make @michaelprimez's library minSDK to 17 but he did not has any activity for months.

**Comment by adin234** [comment]
@bkhezry thanks for noticing, i have also thought of that so i just forked your repository and removed RTL, i hope its fine with you.
